[package]
name = "tb"
authors.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
homepage.workspace = true
edition.workspace = true
version = "0.0.0"
rust-version.workspace = true

[dependencies]
argh.workspace = true
tempdir = "0.3.7"
makemake = "0.1.2-patch2"
figment.workspace = true
serde.workspace = true
