[package]
name = "calyx-ffi-macro"
authors = ["The Calyx Team"]
license-file = "LICENSE"
keywords = ["ir", "compiler"]
repository = "https://github.com/calyxir/calyx"
readme = "README.md"
description = "Compiler Infrastructure for Hardware Accelerator Generation"
categories = ["compilers"]
homepage = "https://calyxir.org"
edition = "2021"
version = "0.7.1"
rust-version = "1.67"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.69", features = ["full", "visit"] }
calyx-utils = { path = "../../calyx-utils/" }
calyx-frontend = { path = "../../calyx-frontend/" }
calyx-ir = { path = "../../calyx-ir/" }
# bigint = "4.4.3"
