[package]
name = "axi-calyx"
authors.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
homepage.workspace = true
edition.workspace = true
version = "0.0.0"
rust-version.workspace = true

[dependencies]
argh.workspace = true
colored.workspace = true
serde.workspace = true
serde_json.workspace = true
yxi = { path = "../../../tools/yxi" }
log.workspace = true
env_logger.workspace = true

# bad, need to figure out how to make it = to workspace
calyx-ir = "0.7.1"
calyx-utils = "0.7.1"

# mirror under MIT
bad-calyx-builder = { git = "https://github.com/ethanuppal/pulsar.git", branch = "relicense" }
