[package]
name = "axi-calyx"
authors.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
homepage.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
argh.workspace = true
colored.workspace = true
serde.workspace = true
serde_json.workspace = true
yxi = { path = "../../../tools/yxi" }

# mirror under MIT
bad-calyx-builder = { git = "https://github.com/ethanuppal/pulsar.git", branch = "relicense" }
