[package]
name = "calyx-ffi-example"
authors.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
homepage.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
path = "test.rs"

[dependencies]
calyx-ffi = { path = "../../../calyx-ffi" }
interp = { path = "../../../../interp" }
calyx-ir.workspace = true
rand = "0.8.5"
