name: Verification

on: [push]

# Ensures that only the latest commit of a PR can execute the actions.
# Useful for cancelling job when a sequence of commits are quickly added.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build VCalyx
    runs-on: ubuntu-latest
    container: ghcr.io/cucapra/calyx:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get bwrap for opam
      run: |
        apt-get update -y
        apt-get install -y bubblewrap
    - name: Set up opam and OCaml
      uses: ocaml/setup-ocaml@v2
      with:
          ocaml-compiler: 4.14.1
    - name: Install dependencies
      run: |
        cd vcalyx
        opam install dune
        opam repo add coq-released https://coq.inria.fr/opam/released
        opam install . --deps-only 
        opam install coq yojson core core_unix ppx_deriving coq-stdpp coq-ceres

    - name: Build Rust
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features serialize --all --manifest-path /home/calyx/interp/Cargo.toml

    - name: Build Coq and OCaml
      run: |
        cd vcalyx
        opam exec -- dune build

    - name: Coq Interpreter Runt Tests
      run: |
        cd vcalyx
        runt --diff --only fail
